RemTestSys/Areas/Editor/Controllers/GroupsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using RemTestSys.Domain.ViewModels;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles="Editor")]
    public class GroupsController : Controller
    {
        public GroupsController(IGroupService groupService)
        {
            this.groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        }
        private readonly IGroupService groupService;
        public async Task<IActionResult> Index()
        {
            return View(await groupService.GetGroupListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)return View("Error");
            var group = await groupService.FindAsync((int)id);
            if (group == null)return NotFound();
            ViewBag.StudentsInGroup = await groupService.GetStudentsForGroupAsync((int)id);
            return View(group);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] GroupViewModel group)
        {
            if (ModelState.IsValid)
            {
                await groupService.CreateAsync(group);
                return RedirectToAction(nameof(Index));
            }
            return View(group);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)return View("Error");
            var group = await groupService.FindAsync((int)id);
            if (group == null)return NotFound();
            return View(group);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name")] GroupViewModel group)
        {
            if (group == null)return View("Error");
            if (ModelState.IsValid)
            {
                if(!groupService.Exists(group.Id))return View("Error");
                await groupService.UpdateAsync(group);
                return RedirectToAction(nameof(Index));
            }
            return View(group);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)return View("Error");
            var group = await groupService.FindAsync((int)id);
            if (group == null)return NotFound();
            return View(group);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if(!groupService.Exists(id))return View("Error");
            await groupService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

RemTestSys/Areas/Editor/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using System;
using System.Threading.Tasks;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles="Editor")]
    public class ResultsController : Controller
    {
        public ResultsController(IExamResultService resultService, IStudentService studentService, IGroupService groupService, IExamService examService)
        {
            this.resultService = resultService ?? throw new ArgumentNullException(nameof(resultService));
            this.studentService = studentService ?? throw new ArgumentNullException(nameof(studentService));
            this.groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
            this.examService = examService ?? throw new ArgumentNullException(nameof(examService));
        }
        private readonly IExamResultService resultService;
        private readonly IStudentService studentService;
        private readonly IGroupService groupService;
        private readonly IExamService examService;
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await resultService.GetResultsAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Student(int id)
        {
            var student = await studentService.FindStudentAsync(id);
            if(student == null)return NotFound();
            ViewData["StudentFullName"]=student.FullName;
            ViewData["StudentId"]=student.Id;
            return View(await resultService.GetResultsOfStudentAsync(id));
        }
        [HttpGet]
        public async Task<IActionResult> Group(int id)
        {
            var group  = await groupService.FindAsync(id);
            if(group == null)return NotFound();
            ViewData["GroupName"] = group.Name;
            ViewData["GroupId"] = group.Id;
            return View(await resultService.GetResultsOfGroupAsync(id));
        }
        [HttpGet]
        public async Task<IActionResult> Test(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if(exam == null)return NotFound();
            ViewData["TestName"]=exam.Name;
            ViewData["TestId"]=exam.Id;
            return View(await resultService.GetResultsOfExamAsync(id));
        }

        [HttpGet]
        public async Task<IActionResult> ClearAll()
        {
            await resultService.ClearResultsAsync();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> ClearForGroup(int id)
        {
            await resultService.ClearResultsOfGroupAsync(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> ClearForStudent(int id)
        {
            await resultService.ClearResultsOfStudentAsync(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> ClearForTest(int id)
        {
            await resultService.ClearResultsOfExamAsync(id);
            return RedirectToAction(nameof(Index));
        }
        
    }
}

RemTestSys/Areas/Editor/Controllers/SessionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using System;
using System.Threading.Tasks;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles="Editor")]
    public class SessionController : Controller
    {
        public SessionController(ISessionService sessionService)
        {
            this.sessionService = sessionService ?? throw new ArgumentNullException(nameof(sessionService));
        }
        private readonly ISessionService sessionService;
        public async Task<IActionResult> Index()
        {
            return View(await sessionService.GetSessionListAsync());
        }
        public async Task<IActionResult> Close(int id)
        {
            await sessionService.CloseSessionAsync(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CloseAll()
        {
            await sessionService.CloseAllSessionsAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

RemTestSys/Areas/Editor/Controllers/TestsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using RemTestSys.Domain.ViewModels;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles="Editor")]
    public class TestsController : Controller
    {
        public TestsController(IExamService examService, IQuestionService questionService)
        {
            this.examService = examService ?? throw new ArgumentNullException(nameof(examService));
            this.questionService = questionService ?? throw new ArgumentNullException(nameof(questionService));
        }
        private readonly IExamService examService;
        private readonly IQuestionService questionService;
        public async Task<IActionResult> Index()
        {
            return View(await examService.GetExamsAsync());
        }
        public async Task<IActionResult> Details(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if (exam == null)return NotFound();
            ViewBag.QuestionsInExam = await questionService.GetQuestionsFromExamAsync(id);
            return View(exam);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExamViewModel exam)
        {
            if (ModelState.IsValid)
            {
                await examService.CreateExamAsync(exam);
                return RedirectToAction(nameof(Index));
            }
            return View(exam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if(exam == null)return NotFound();
            return View(exam);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExamViewModel examViewModel)
        {
            if (ModelState.IsValid)
            {
                await examService.UpdateExamAsync(examViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(examViewModel);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if(exam == null)return NotFound();
            return View(exam);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await examService.DeleteExamAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

RemTestSys/Areas/Editor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Maksim Kasyanenko" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
</head>
<body style="position: relative;">
    @await Html.PartialAsync("_SpecialSymbolsPanelHidden")
    <header class="bg-dark bg-gradient mb-4">
        <div class="container">
            <ul class="nav">
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Results" class="nav-link text-white">Результати тестів</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Tests" class="nav-link text-white">Тести</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Accesses" class="nav-link text-white">Доступ</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Groups" class="nav-link text-white">Групи</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Students" class="nav-link text-white">Учні</a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Session" class="nav-link text-white">Сессії</a>
                </li>
            </ul>
        </div>
    </header>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

RemTestSys/Areas/Editor/Views/Shared/_SpecialSymbolsPanelHidden.cshtml
<div id="specSymPanHidden" class="bg-white border shadow p-1" style="position:absolute; display:none;">
    <div class="text-end"><button type="button" onclick="hidePanel();" class="p-1 btn btn-danger">X</button></div>
    @await Html.PartialAsync("SpecialSymbolsPanel")
</div>
<script>
    window.addEventListener("load", function () {
        let inputs = document.querySelectorAll("input[type='text'], textarea");
        let panel = document.getElementById("specSymPanHidden");
        for (let inpt of inputs) {
            inpt.addEventListener("focus", function () {
                panel.style.display = "block";
                let b = inpt.getBoundingClientRect();
                panel.style.top = (window.pageYOffset + b.top - panel.offsetHeight) + "px";
                panel.style.left = window.pageXOffset + b.left + "px";
            });
        }
    });
    function hidePanel() {
        document.getElementById("specSymPanHidden").style.display = "none";
    }
</script>