RemTestSys/Areas/Editor/Controllers/AccessesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using System;
using System.Threading.Tasks;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles = "Editor")]
    public class AccessesController : Controller
    {
        public AccessesController(IExamAccessService accessService, IGroupService groupService, IStudentService studentService)
        {
            this.accessService = accessService ?? throw new ArgumentNullException(nameof(accessService));
            this.groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
            this.studentService = studentService ?? throw new ArgumentNullException(nameof(studentService));
        }
        private readonly IExamAccessService accessService;
        private readonly IGroupService groupService;
        private readonly IStudentService studentService;
        public async Task<IActionResult> Index()
        {
            return View(await accessService.GetAccessListAsync());
        }
        public async Task<IActionResult> OpenAccessToTestForAll(int id)
        {
            await accessService.OpenCommonAccessAsync(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> OpenAccessToTestForGroup(int id)
        {
            ViewData["TestId"] = id;
            var groups = await groupService.GetGroupListAsync();
            return View(groups);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OpenAccessToTestForGroup(int id, int testId)
        {
            await accessService.OpenGroupAccessAsync(id, testId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> OpenAccessToTestForStudent(int id)
        {
            ViewData["TestId"] = id;
            var students = await studentService.GetStudentsAsync();
            return View(students);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OpenAccessToTestForStudent(int id, int testId)
        {
            await accessService.OpenPersonAccessAsync(id, testId);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ClearAll()
        {
            await accessService.CloseAllAccessesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteForAll(int id)
        {
            await accessService.CloseCommonAccessAsync(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteForGroups(int id)
        {
            await accessService.CloseGroupAccessAsync(id);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteForStudent(int id)
        {
            await accessService.ClosePersonAccessAsync(id);
            return RedirectToAction("Index");
        }
    }
}

RemTestSys/Areas/Editor/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RemTestSys.Areas.Editor.ViewModel;
using RemTestSys.Domain;
using RemTestSys.Domain.Models;
using RemTestSys.Domain.ViewModels;
using RemTestSys.Domain.Interfaces;
using RemTestSys.Domain.ViewModels.QuestionsWithAnswers;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles = "Editor")]
    public class QuestionsController : Controller
    {
        public QuestionsController(IQuestionService questionService, IExamService examService, AppDbContext dbContext)
        {
            this.dbContext = dbContext;
            this.examService = examService ?? throw new ArgumentNullException(nameof(examService));
            this.questionService = questionService ?? throw new ArgumentNullException(nameof(questionService));
        }
        private readonly IExamService examService;
        private readonly IQuestionService questionService;
        private readonly AppDbContext dbContext;


        [HttpGet]
        public async Task<IActionResult> CreateTextAnswer(int id) => await GetViewToCreateQuestion(nameof(CreateTextAnswer), id);
        [HttpGet]
        public async Task<IActionResult> CreateOneOfFourAnswer(int id) => await GetViewToCreateQuestion(nameof(CreateOneOfFourAnswer), id);
        [HttpGet]
        public async Task<IActionResult> CreateSomeAnswer(int id) => await GetViewToCreateQuestion(nameof(CreateSomeAnswer), id);
        [HttpGet]
        public async Task<IActionResult> CreateSequenceAnswer(int id) => await GetViewToCreateQuestion(nameof(CreateSequenceAnswer), id);
        [HttpGet]
        public async Task<IActionResult> CreateConnectedPairsAnswer(int id) => await GetViewToCreateQuestion(nameof(CreateConnectedPairsAnswer), id);
        private async Task<IActionResult> GetViewToCreateQuestion(string actionName, int examId)
        {
            var exam = await examService.FindExamAsync(examId);
            if (exam == null) return NotFound();
            ViewData["TestId"] = exam.Id;
            return View(actionName);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTextAnswer(QuestionWithTextAnswerViewModel question) => await CreateQuestionWithAnswer(question);
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOneOfFourAnswer(QuestionWithOneOfFourVariantsAnswerViewModel question) => await CreateQuestionWithAnswer(question);
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSomeAnswer(QuestionWithSomeVariantsAnswerViewModel question) => await CreateQuestionWithAnswer(question);
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSequenceAnswer(QuestionWithSequenceAnswerViewModel question) => await CreateQuestionWithAnswer(question);
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateConnectedPairsAnswer(QuestionWithConnectedPairsAnswerViewModel question) => await CreateQuestionWithAnswer(question);
        private async Task<IActionResult> CreateQuestionWithAnswer(QuestionWithAnswerViewModel question)
        {
            if(ModelState.IsValid)
            {
                await questionService.AddQuestionWithAnswerAsync(question);
                return RedirectToAction("Details", "Tests", new { id = question.ExamId });
            }
            else
            {
                ModelState.AddModelError("", "Присутні невірні данні");
                ViewData["TestId"] = question.ExamId;
                return View(question);
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var question = await questionService.FindQuestionWithAnswerAsync(id);
            if (question == null) return RedirectToAction("Index", "Tests");
            Type questionType = question.GetType();
            if(questionType == typeof(QuestionWithTextAnswerViewModel))
            {
                return View("EditTextAnswer", question);
            }
            else if(questionType == typeof(QuestionWithOneOfFourVariantsAnswerViewModel))
            {
                return View("EditOneOfFourAnswer", question);
            }else if(questionType == typeof(QuestionWithSomeVariantsAnswerViewModel))
            {
                return View("EditSomeVariantsAnswer", question);
            }else if(questionType == typeof(QuestionWithSequenceAnswerViewModel))
            {
                return View("EditSequenceAnswer", question);
            }
            else if(questionType == typeof(QuestionWithConnectedPairsAnswerViewModel))
            {
                return View("EditConnectedPairAnswer", question);
            }
            return View("Error");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTextAnswer(QuestionWithTextAnswerViewModel vm){
            await questionService.UpdateQuestionWithAnswerAsync(vm);
            return RedirectToAction("Details","Tests",new {id=vm.ExamId});
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOneOfFourAnswer(QuestionWithOneOfFourVariantsAnswerViewModel vm){
            await questionService.UpdateQuestionWithAnswerAsync(vm);
            return RedirectToAction("Details","Tests",new {id=vm.ExamId});
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSomeVariantsAnswer(QuestionWithSomeVariantsAnswerViewModel vm)
        {
            await questionService.UpdateQuestionWithAnswerAsync(vm);
            return RedirectToAction("Details","Tests",new {id=vm.ExamId});
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSequenceAnswer(QuestionWithSequenceAnswerViewModel vm)
        {
            await questionService.UpdateQuestionWithAnswerAsync(vm);
            return RedirectToAction("Details","Tests",new {id=vm.ExamId});
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditConnectedPairAnswer(QuestionWithConnectedPairsAnswerViewModel vm)
        {
            await questionService.UpdateQuestionWithAnswerAsync(vm);
            return RedirectToAction("Details","Tests",new {id=vm.ExamId});
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            var q = await questionService.FindQuestionWithAnswerAsync(id);
            if(q == null)return NotFound();
            return View(q);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ConfirmedDeleteForQuestionViewModel confirmedDelete)
        {
            await questionService.DeleteAsync(confirmedDelete.Id);
            return RedirectToAction("Details", "Tests", new { id = confirmedDelete.TestId });
        }
    }
}

RemTestSys/Areas/Editor/Controllers/TestsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RemTestSys.Domain.Interfaces;
using RemTestSys.Domain.ViewModels;

namespace RemTestSys.Areas.Editor.Controllers
{
    [Area("Editor")]
    [Authorize(Roles="Editor")]
    public class TestsController : Controller
    {
        public TestsController(IExamService examService, IQuestionService questionService)
        {
            this.examService = examService ?? throw new ArgumentNullException(nameof(examService));
            this.questionService = questionService ?? throw new ArgumentNullException(nameof(questionService));
        }
        private readonly IExamService examService;
        private readonly IQuestionService questionService;
        public async Task<IActionResult> Index()
        {
            return View(await examService.GetExamsAsync());
        }
        public async Task<IActionResult> Details(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if (exam == null)return NotFound();
            ViewBag.QuestionsInExam = await questionService.GetQuestionsFromExamAsync(id);
            return View(exam);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExamViewModel exam)
        {
            if (ModelState.IsValid)
            {
                await examService.CreateExamAsync(exam);
                return RedirectToAction(nameof(Index));
            }
            return View(exam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if(exam == null)return NotFound();
            return View(exam);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ExamViewModel examViewModel)
        {
            if (ModelState.IsValid)
            {
                await examService.UpdateExamAsync(examViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(examViewModel);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var exam = await examService.FindExamAsync(id);
            if(exam == null)return NotFound();
            return View(exam);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await examService.DeleteExamAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

RemTestSys/Areas/Editor/Views/Tests/Create.cshtml
@model RemTestSys.Domain.ViewModels.ExamViewModel

@{
    ViewData["Title"] = "Новий тест";
}

<h2>Новий тест</h2>
<hr />
<div class="row">
    <div class="col-md-6 mx-auto">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис(необов'язково)</label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group mb-2">
                <label asp-for="Duration" class="control-label">Час на проходження тесту(сек.)</label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>

            <div class="p-2 border mb-2">
                <h4>Розподіл питань</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Кількість питань</th>
                            <th>Ціною</th>
                        </tr>
                    </thead>
                    <tbody id="testMap">
                        <tr>
                            <td><input name="MapParts[0].QuestionCount" class="form-control" /></td>
                            <td><input name="MapParts[0].QuestionCost" class="form-control" /></td>
                        </tr>
                    </tbody>
                </table>
                <div class="text-center">
                    <button type="button" onclick="addMapPart();" class="btn btn-primary">+</button>
                    <button type="button" onclick="removeMapPart();" class="btn btn-danger">-</button>
                </div>
                <script>
                    let mapPartCounter = 0;
                    function addMapPart() {
                        mapPartCounter++;
                        let row = `<tr>
                                                                    <td><input name="MapParts[${mapPartCounter}].QuestionCount" class="form-control" /></td>
                                                                    <td><input name="MapParts[${mapPartCounter}].QuestionCost" class="form-control" /></td>
                                                               </tr>`;
                        document.getElementById("testMap").insertAdjacentHTML("beforeEnd", row);
                    }
                    function removeMapPart() {
                        mapPartCounter--;
                        let map = document.getElementById("testMap");
                        map.removeChild(map.lastElementChild);
                    }
                </script>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

RemTestSys/Areas/Editor/Views/Tests/Delete.cshtml
@model RemTestSys.Domain.ViewModels.ExamViewModel

@{
    ViewData["Title"] = "Видалення тесту";
}

<h2>Видалення тесту</h2>
<p class="text-danger">Ви впевнені, що хочете видалити цей тест? Всі питання, що входять до тесту також будуть видалені!</p>
<div>
    <h4>Тест</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Назва
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>
        <dt class="col-sm-2">
            Опис
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="mb-4">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Видалити" class="btn btn-danger" />
        </div>
        <a asp-action="Index">Назад до списку</a>
    </form>
</div>

RemTestSys/Areas/Editor/Views/Tests/Details.cshtml
@model RemTestSys.Domain.ViewModels.ExamViewModel

@{
    ViewData["Title"] = "Деталі";
}
<h4>Деталі по тесту '@Model.Name' </h4>
<hr />
<div class="mb-4">
    <dl class="row mb-4">
        <dt class="col-sm-2">
            Опис
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
        <dt class="col-sm-2">
            Часу на проходження(сек.)
        </dt>
        <dd class="col-sm-10">
            @Model.Duration
        </dd>
        <dt class="col-sm-2">
            Кількість питань
        </dt>
        <dd class="col-sm-10">
            @Model.QuestionCount
        </dd>
        <dt class="col-sm-2">
            Максимальна оцінка
        </dt>
        <dd class="col-sm-10">
            @Model.MaxMark
        </dd>
    </dl>
    <h4>Розподіл питань</h4>
    <hr />
    <div class="mb-4">
        @foreach(var part in Model.MapParts)
        {
            <p>@($"{part.QuestionCount} питань по {part.QuestionCost} балів")</p>
        }
    </div>
    <h4>Доступ</h4>
    <hr />
        <div class="mb-4">
            <a asp-action="OpenAccessToTestForAll" asp-controller="Accesses" asp-route-id="@Model.Id">Відкрити для всіх</a> | 
            <a asp-action="OpenAccessToTestForGroup" asp-controller="Accesses" asp-route-id="@Model.Id">Відкрити для групи</a> | 
            <a asp-action="OpenAccessToTestForStudent" asp-controller="Accesses" asp-route-id="@Model.Id">Відкрити для учня</a>
        </div>
    <h4>Питання тесту</h4>
    <hr />
            @if (((IEnumerable<object>)ViewBag.QuestionsInExam).Count() > 0)
            {
                <table class="table table-bordered table-striped table-success">
                    <thead>
                        <tr>
                            <th>
                                Питання
                            </th>
                            <th>
                                Відповідь
                            </th>
                            <th>Балів за відповідь</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var question in ViewBag.QuestionsInExam)
                        {
                            <tr>
                                <td>
                                    @question.Text
                                </td>
                                <td>
                                    @question.RightAnswer
                                </td>
                                <td>@question.Cost</td>
                                <td>
                                    <a asp-action="Edit" asp-controller="Questions" asp-route-id="@question.Id">Редагувати</a> | 
                                    <a asp-action="Delete" asp-controller="Questions" asp-route-id="@question.Id">Видалити</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p class="text-center">В данному тесті немає жодного запитання</p>
            }
            <div class="border p-1">
                <span class="text-primary fw-bold">Створити питання : </span>
                <a class="link-secondary" asp-action="CreateTextAnswer" asp-controller="Questions" asp-route-id="@Model.Id">Текст</a> |
                <a class="link-secondary" asp-action="CreateOneOfFourAnswer" asp-controller="Questions" asp-route-id="@Model.Id">1 з 4</a> |
                <a class="link-secondary" asp-action="CreateSomeAnswer" asp-controller="Questions" asp-route-id="@Model.Id">Декілька варіантів</a> |
                <a class="link-secondary" asp-action="CreateSequenceAnswer" asp-controller="Questions" asp-route-id="@Model.Id">Послідовність</a> |
                <a class="link-secondary" asp-action="CreateConnectedPairsAnswer" asp-controller="Questions" asp-route-id="@Model.Id">Пари</a>
            </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редагувати тест</a> |
    <a asp-action="Index">Назад до списку</a>
</div>

RemTestSys/Areas/Editor/Views/Tests/Edit.cshtml
@model RemTestSys.Domain.ViewModels.ExamViewModel

@{
    ViewData["Title"] = "Редагувати тест";
}

<h2>Редагування тесту</h2>
<hr />
<div class="row">
    <div class="col-md-6 mx-auto">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Duration" class="control-label">Час на проходження(сек.)</label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>

            <div class="p-2 border mb-2">
                <h4>Розподіл питань</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Кількість питань</th>
                            <th>Ціною</th>
                        </tr>
                    </thead>
                    <tbody id="testMap">
                        @if (Model.MapParts != null && Model.MapParts.Count() > 0)
                        {
                            @for(int i=0;i<Model.MapParts.Count();i++)
                            {
                                <tr>
                                    <td><input name="MapParts[@i].QuestionCount" class="form-control" value="@Model.MapParts.ToArray()[i].QuestionCount" /></td>
                                    <td><input name="MapParts[@i].QuestionCost" class="form-control" value="@Model.MapParts.ToArray()[i].QuestionCost" /></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div class="text-center">
                    <button type="button" onclick="addMapPart();" class="btn btn-primary">+</button> 
                    <button type="button" onclick="removeMapPart();" class="btn btn-danger">-</button>
                </div>
                <script>
                    let mapPartCounter = @(Model.MapParts.Count()-1);
                    function addMapPart() {
                        mapPartCounter++;
                        let row = `<tr>
                                                                    <td><input name="MapParts[${mapPartCounter}].QuestionCount" class="form-control" /></td>
                                                                    <td><input name="MapParts[${mapPartCounter}].QuestionCost" class="form-control" /></td>
                                                               </tr>`;
                        document.getElementById("testMap").insertAdjacentHTML("beforeEnd", row);
                    }
                    function removeMapPart() {
                        mapPartCounter--;
                        let map = document.getElementById("testMap");
                        map.removeChild(map.lastElementChild);
                    }
                </script>
            </div>

            <div class="form-group text-center">
                <input type="submit" value="Зберегти зміни" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

RemTestSys/Areas/Editor/Views/Tests/Index.cshtml
@model IEnumerable<RemTestSys.Domain.ViewModels.ExamViewModel>

@{
    ViewData["Title"] = "Всі тести";
}

<h2>Всі тести</h2>

<p class="text-end">
    <a asp-action="Create" class="btn btn-primary">Створити новий</a>
</p>
@if (Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-2">
                    Назва
                </th>
                <th class="col-2">
                    Опис
                </th>
                <th class="col">
                    Кількість питань
                </th>
                <th class="col">
                    Часу на проходження
                </th>
                <th class="col">
                    Максимальна оцінка
                </th>
                <th class="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.QuestionCount
                    </td>
                    <td>
                        @item.Duration
                    </td>
                    <td>
                        @item.MaxMark
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p class="text-center text-secondary">Не знайдено жодного тесту</p>
}